install.packages("pdftools")
install.packages("stringr")
install.packages("tidyverse")
install.packages("tidytext")
install.packages("wordcloud")
install.packages("RColorBrewer")
install.packages("here")
install.packages("quanteda")
install.packages("googledrive")
install.packages("kableExtra")
install.packages("httr")
install.packages("xml2")
install.packages("rvest")
install.packages("tidyr")
install.packages("ggplot2")
remotes::install_github("tidyverse/googledrive", ref = "v1.0.0") # more convenience for upload/update in newer version
